version: "3.9"
services:
  report2zabbix:
    image: "report2zabbix"
    container_name: monitoring
    environment: 
      BEAM_URL: "http://192.168.0.199:8082"
      PROXY_ID: "zabbix.niclas-dev.broker.dev.ccp-it.dktk.dkfz.de"
      ZABBIX_API_URL: "http://192.168.0.60/zabbix/api_jsonrpc.php"
      ZABBIX_SERVER_URL: "192.168.0.60"
      KEY: "1234"
    